[package]
name = "qbot"
version = "0.2.0"
authors = ["Eric Huff <thegreaterici@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
config = "0.10.1"
log = "0.4.14"
simple_logger = "1.11"
tokio = { version = "1.2", features = ["full"] }
warp = "0.3"
irc = "0.15"
futures = "0.3"
serde = { version = "1.0", features = ["rc"] }
serde_json = "1.0"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
chrono = { version = "0.4", features = ["serde"] }
reqwest = "0.11"
