version: "3"
services:
  rust-dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: sleep infinity
    env_file: ./devcontainer.env
  db:
    image: "postgres:14"
    restart: unless-stopped
    env_file: ./devcontainer.env
  nginx:
    build:
      context: .
      dockerfile: webserver.dockerfile
    restart: unless-stopped
    env_file: ./devcontainer.env
