version: "3"
services:
  rust-dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: sleep infinity
    network_mode: service:db
    env_file: ./devcontainer.env
  db:
    image: "postgres:13"
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: ./devcontainer.env
  nginx:
    image: nginx:stable
    restart: unless-stopped

volumes:
  db_data:
